import type { Metadata } from "next";
import "flag-icons/css/flag-icons.min.css";
import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.css";
import { twMerge } from "tailwind-merge";
import SmoothScroll from "@/components/animation/smooth-scroll";
import { inter } from "@/assets/styles/fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";
import GlobalContextProvider from "@/context/GlobalContext";

export const metadata: Metadata = {
  title: "Groves",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-clip bg-black">
      <body className={twMerge(inter.className, "bg-gradient-to-br from-[#283606] to-[#0F1500] text-white")}>
        <div id="groves-video-player"></div>
        <SmoothScroll />
        <GlobalContextProvider>
          <Header />
          {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
